base_url = "https://wisn.ch"

title = "wisn.channeling"
description = "an ever-growing personal archive to store thoughts, stories, writings, and many more"
default_language = "en"
author = "wisn"

compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]
minify_html = true

[markdown]
highlight_code = true

[extra]
